### PR TITLE
PAINTROID-244 Cannot load jpg format in Android 5 and 6

### PR DESCRIPTION
**Pull request by CodeChamp-SS**
Fixed loading of images in android 5 and 6

https://jira.catrob.at/browse/PAINTROID-244

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Paintroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [x] Include the name of the Jira ticket in the PR’s title
- [x] Include a summary of the changes plus the relevant context
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [ ] Verify that the changes generate no compiler or linter warnings
- [x] Perform a self-review of the changes
- [x] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [x] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [x] Stick to the project’s gitflow workflow
- [x] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [x] Post a message in the *#paintroid* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

### CODE REVIEW

**Review by wslany — CHANGES_REQUESTED** [review]
Thanks. There were some failures in the build, as follows:
```
04:25:28  > Task :Paintroid:compileDebugAndroidTestJavaWithJavac FAILED
04:25:28  /home/catroid/jenkins_slave/workspace/Paintroid_PR-880/Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/FileFromOtherSourceIntegrationTest.java:67: error: method getBitmapFromUri in class FileIO cannot be applied to given types;
04:25:28  			receivedBitmap = FileIO.getBitmapFromUri(resolver, receivedUri);
04:25:28  			                       ^
04:25:28    required: ContentResolver,Uri,Context
04:25:28    found: ContentResolver,Uri
04:25:28    reason: actual and formal argument lists differ in length
04:25:28  /home/catroid/jenkins_slave/workspace/Paintroid_PR-880/Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/FileFromOtherSourceIntegrationTest.java:96: error: method getBitmapFromUri in class FileIO cannot be applied to given types;
04:25:28  			mainActivityIntentBitmap = FileIO.getBitmapFromUri(resolver, mainActivityIntentUri);
04:25:28  			                                 ^
04:25:28    required: ContentResolver,Uri,Context
```

**Comment by CodeChamp-SS** [comment]
> Thanks. There were some failures in the build, as follows:
> 
> ```
> 04:25:28  > Task :Paintroid:compileDebugAndroidTestJavaWithJavac FAILED
> 04:25:28  /home/catroid/jenkins_slave/workspace/Paintroid_PR-880/Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/FileFromOtherSourceIntegrationTest.java:67: error: method getBitmapFromUri in class FileIO cannot be applied to given types;
> 04:25:28  			receivedBitmap = FileIO.getBitmapFromUri(resolver, receivedUri);
> 04:25:28  			                       ^
> 04:25:28    required: ContentResolver,Uri,Context
> 04:25:28    found: ContentResolver,Uri
> 04:25:28    reason: actual and formal argument lists differ in length
> 04:25:28  /home/catroid/jenkins_slave/workspace/Paintroid_PR-880/Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/FileFromOtherSourceIntegrationTest.java:96: error: method getBitmapFromUri in class FileIO cannot be applied to given types;
> 04:25:28  			mainActivityIntentBitmap = FileIO.getBitmapFromUri(resolver, mainActivityIntentUri);
> 04:25:28  			                                 ^
> 04:25:28    required: ContentResolver,Uri,Context
> ```

I'll fix them asap.

**Comment by CodeChamp-SS** [comment]
> Thanks. There were some failures in the build, as follows:
> 
> https://jenkins.catrob.at/job/Paintroid/job/PR-880/1/execution/node/56/log/
> 
> ```
> 04:25:28  > Task :Paintroid:compileDebugAndroidTestJavaWithJavac FAILED
> 04:25:28  /home/catroid/jenkins_slave/workspace/Paintroid_PR-880/Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/FileFromOtherSourceIntegrationTest.java:67: error: method getBitmapFromUri in class FileIO cannot be applied to given types;
> 04:25:28  			receivedBitmap = FileIO.getBitmapFromUri(resolver, receivedUri);
> 04:25:28  			                       ^
> 04:25:28    required: ContentResolver,Uri,Context
> 04:25:28    found: ContentResolver,Uri
> 04:25:28    reason: actual and formal argument lists differ in length
> 04:25:28  /home/catroid/jenkins_slave/workspace/Paintroid_PR-880/Paintroid/src/androidTest/java/org/catrobat/paintroid/test/espresso/FileFromOtherSourceIntegrationTest.java:96: error: method getBitmapFromUri in class FileIO cannot be applied to given types;
> 04:25:28  			mainActivityIntentBitmap = FileIO.getBitmapFromUri(resolver, mainActivityIntentUri);
> 04:25:28  			                                 ^
> 04:25:28    required: ContentResolver,Uri,Context
> ```

fixed it : ), please do lemme know if any further changes are required.

**Comment by wslany** [comment]
Please resolve the merge conflicts. See #884 for changes.

**Comment by CodeChamp-SS** [comment]
> Please resolve the merge conflicts. See #884 for changes.

done : )

**Comment by wslany** [comment]
Thanks! 🙏 See my DM on slack regarding how to find a code reviewer.

**Review by ldirry — APPROVED** [review]
Looks good to me :)

**Review by wslany — CHANGES_REQUESTED** [review]
I don't know what happened but now I get this (same standard jpg I'm always using for testing):
image

It works fine with Android 5.0, 5.1 and 7.0, but not with Android 6.0. 

I also tried on a Nexus 6 with Android 6.0, there when I load a jpg the app stops, like this:
image

Nexus 7 Android 6.0:
image

Here's the stacktrace:
```
04-26 15:42:32.601 E/AndroidRuntime( 7964): FATAL EXCEPTION: AsyncTask #1
04-26 15:42:32.601 E/AndroidRuntime( 7964): Process: org.catrobat.paintroid.independent_20210426_1332, PID: 7964
04-26 15:42:32.601 E/AndroidRuntime( 7964): java.lang.RuntimeException: An error occurred while executing doInBackground()
04-26 15:42:32.601 E/AndroidRuntime( 7964): 	at android.os.AsyncTask$3.done(AsyncTask.java:309)
04-26 15:42:32.601 E/AndroidRuntime( 7964): 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
04-26 15:42:32.601 E/AndroidRuntime( 7964): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
04-26 15:42:32.601 E/AndroidRuntime( 7964): 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
04-26 15:42:32.601 E/AndroidRuntime( 7964): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
04-26 15:42:32.601 E/AndroidRuntime( 7964): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
04-26 15:42:32.601 E/AndroidRuntime( 7964): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
04-26 15:42:32.601 E/AndroidRuntime( 7964): 	at java.lang.Thread.run(Thread.java:818)
04-26 15:42:32.601 E/AndroidRuntime( 7964): Caused by: java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/images/media from pid=7964, uid=10092 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()
04-26 15:42:32.601 E/AndroidRuntime( 7964): 	at android.os.Parcel.readException(Parcel.java:1620)
04-26 15:42:32.601 E/AndroidRuntime( 7964): 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
04-26 15:42:32.601 E/AndroidRuntime( 7964): 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
04-26 15:42:32.601 E/AndroidRuntime( 7964): 	at android.content.ContentProviderProxy.query(ContentProviderNative.java:421)
04-26 15:42:32.601 E/AndroidRuntime( 7964): 	at android.content.ContentResolver.query(ContentResolver.java:491)
04-26 15:42:32.601 E/AndroidRuntime( 7964): 	at android.content.ContentResolver.query(ContentResolver.java:434)
04-26 15:42:32.601 E/AndroidRuntime( 7964): 	at org.catrobat.paintroid.presenter.MainActivityPresenter.getDataColumn(MainActivityPresenter.java:838)
04-26 15:42:32.601 E/AndroidRuntime( 7964): 	at org.catrobat.paintroid.presenter.MainActivityPresenter.getPathFromUri(MainActivityPresenter.java:815)
04-26 15:42:32.601 E/AndroidRuntime( 7964): 	at org.catrobat.paintroid.FileIO.getBitmapOrientationFromUri(FileIO.java:231)
04-26 15:42:32.601 E/AndroidRuntime( 7964): 	at org.catrobat.paintroid.FileIO.decodeBitmapFromUri(FileIO.java:206)
04-26 15:42:32.601 E/AndroidRuntime( 7964): 	at org.catrobat.paintroid.FileIO.getBitmapReturnValueFromUri(FileIO.java:418)
04-26 15:42:32.601 E/AndroidRuntime( 7964): 	at org.catrobat.paintroid.iotasks.LoadImageAsync.doInBackground(LoadImageAsync.kt:70)
04-26 15:42:32.601 E/AndroidRuntime( 7964): 	at org.catrobat.paintroid.iotasks.LoadImageAsync.doInBackground(LoadImageAsync.kt:32)
04-26 15:42:32.601 E/AndroidRuntime( 7964): 	at android.os.AsyncTask$2.call(AsyncTask.java:295)
04-26 15:42:32.601 E/AndroidRuntime( 7964): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
```

Just for completeness, I also checked on Android 5.1 and there it still works fine:
image

**Review by wslany — APPROVED** [review]

**Review by ldirry — APPROVED** [review]
